spring:
  application:
    name: remind

  ai:
    ollama:
      base-url: http://127.0.0.1:20251
      chat:
        options:
          model: gemma3:12b
          temperature: 0.1

      embedding:
        options:
          model: bge-m3

  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/remind
    username: postgres
    password: "0514"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
