spring:
  application:
    name: remind

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: qwen2.5:3b

      embedding:
        options:
          model: bge-m3

  datasource:
    url: jdbc:postgresql://localhost:5432/remind
    username: postgres
    password: "0514"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true