spring:
  application:
    name: remind

  ai:
    ollama:
      base-url: http://168.188.128.36:20251

      chat:
        options:
          model: exaone3.5


      embedding:
        options:
          model: bge-m3

  datasource:
    url: jdbc:postgresql://localhost:5432/remind
    username: postgres
    password: "0514"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
